2020-02-15 10:35:18,432 ERROR: Exception on /home/ [GET] [in /home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/avenger/workspace/projects/startupMinds/app/views.py", line 45, in home
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/avenger/workspace/projects/startupMinds/app/templates/home.html", line 2, in top-level template code
    {%import "bootstrap/wtf.html" as wtf%}
  File "/home/avenger/workspace/projects/startupMinds/app/templates/theme.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 6, in block "html"
    {%- block head %}
  File "/home/avenger/workspace/projects/startupMinds/app/templates/theme.html", line 9, in block "head"
    {{ fontawesome_css() }}
jinja2.exceptions.UndefinedError: 'fontawesome_css' is undefined
2020-02-15 10:35:19,310 ERROR: Exception on /stories/ [GET] [in /home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/avenger/workspace/projects/startupMinds/app/views.py", line 184, in stories
    page = request.args.get('page', 1, type=int)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/avenger/workspace/projects/startupMinds/app/templates/stories.html", line 2, in top-level template code
    {%import "bootstrap/wtf.html" as wtf%}
  File "/home/avenger/workspace/projects/startupMinds/app/templates/theme.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/avenger/workspace/projects/startupMinds/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 6, in block "html"
    {%- block head %}
  File "/home/avenger/workspace/projects/startupMinds/app/templates/theme.html", line 9, in block "head"
    {{ fontawesome_css() }}
jinja2.exceptions.UndefinedError: 'fontawesome_css' is undefined
